services:
  broker:
    container_name: broker
    image: eclipse-mosquitto:2.1-alpine
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./mosquitto/data:/mosquitto/data"
  simulator:
    container_name: simulator
    build:
      dockerfile: simulator/Dockerfile
      context: ./simulator
    profiles: ["simulation"]
    env_file:
      - ./simulator/.env
    depends_on:
      broker:
        condition: service_started
