"""Add index (node_id,time) for readings

Revision ID: a897f164ce03
Revises: ae906f589b43
Create Date: 2026-08-05 21:45:28.382101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a897f164ce03'
down_revision: Union[str, Sequence[str], None] = 'ae906f589b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reading_time_node_id', 'readings', ['node_id', 'time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reading_time_node_id', table_name='readings')
    # ### end Alembic commands ###
